
--granting permissions from the SYSTEM user level

ALTER SESSION SET CONTAINER = XEPDB1

CREATE USER APTEKA IDENTIFIED BY  ****;
ALTER USER APTEKA IDENTIFIED BY  ****;

GRANT CREATE SESSION TO APTEKA;
GRANT ALL PRIVILEGES TO APTEKA;	 
GRANT CREATE PROCEDURE TO APTEKA; 

-- do włączenia
GRANT CONNECT TO APTEKA;
GRANT CREATE SESSION, GRANT ANY PRIVILEGE TO APTEKA;
GRANT UNLIMITED TABLESPACE TO APTEKA;
GRANT CREATE TABLE TO APTEKA;